### ISSUE TITLE
Load GUFF from assets?

### ISSUE THREAD

**Issue by LondonX** [BrutalCoding/aub.ai#13]
Hi,

Say I put my guff in assets and added in yaml like this

```yaml
flutter:
  assets:
    - assets/bin/
```

Can or will it be possible to use it like `talkAsync`, without dump the file into App's files dir?
