### ISSUE TITLE
Unable to generate binding using latest llama.cpp

### ISSUE THREAD

**Issue by ndnam198** [BrutalCoding/aub.ai#24]
### Unable to generate binding using latest llama.cpp

After several trials and fail to run the app with the current generated bindings on repo's master branch (I cannot initialize the model following either aub's step or my step follow some llama.cpp usage guidelines. 
I think there may be some light if I generate again the binding but again cannot succeed to do so 

I got this error when trying to run the ffigen command 

```txt
[SEVERE] : Header ./src/llama.cpp/include/llama.h: Total errors/warnings: 1.
[SEVERE] :     ./src/llama.cpp/include/llama.h:4:10: fatal error: 'ggml.h' file not found [Lexical or Preprocessor Issue]
```

and I had to modify the ffigen.yaml a bit as I believed paths there were configured incorrectly, but mostly they stay same

```yaml
# Run with `flutter pub run ffigen --config ffigen.yaml`.
name: AubAiBindings
description: |
  Bindings for `src/aub_ai.h`.

  Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
output: "lib/aub_ai_bindings_generated.dart"
headers:
  entry-points:
    - "src/aub_ai.h"
    - "src/llama.cpp/include/llama.h" <-- this I added the /include cause there is no `llama.h` inside llama.cpp but under include
    - 'src/sherpa-onnx/sherpa-onnx/c-api/c-api.h'
  include-directives:
    - "src/aub_ai.h"
    - "src/llama.cpp/include/llama.h" 
    - 'src/sherpa-onnx/sherpa-onnx/c-api/c-api.h'
preamble: |
  // ignore_for_file: always_specify_types
  // ignore_for_file: camel_case_types
  // ignore_for_file: non_constant_identifier_names
  // ignore_for_file: deprecated_member_use
  // ignore_for_file: unused_field
compiler-opts-automatic: // <-- this Is new 
  macos:
    include-c-standard-library: true
comments:
  style: any
  length: full
```

Please help with the re-generation and maybe better help to run the app successfully without making much changes. I am not sure if anyone could succeed running their local AI using this plugin, please help out if you know where the problem lives. 

Thanks
